# Generated by Django 5.0.6 on 2024-06-06 20:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_flat_owner_pure_phone_alter_flat_has_balcony_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='liked_by',
            field=models.ManyToManyField(blank=True, null=True, related_name='liked_appartment', to=settings.AUTH_USER_MODEL, verbose_name='Кто лайкнул'),
        ),
    ]
