# Generated by Django 5.0.6 on 2024-06-06 20:52

from django.db import migrations
import phonenumbers




def get_owner_pure_phone(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        owner_pure_phonenumber = phonenumbers.parse(flat.owners_phonenumber, 'RU')
        if phonenumbers.is_valid_number(owner_pure_phonenumber):
            flat.owner_pure_phone = owner_pure_phonenumber
        else:
            flat.owner_pure_phone = None
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_alter_flat_liked_by'),
    ]

    operations = [
        migrations.RunPython(get_owner_pure_phone)
    ]
