# Generated by Django 5.0.6 on 2024-06-14 20:30

from django.db import migrations


def get_flat_owner(apps, shcema_epitor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all():
        Owner.objects.get_or_create(
            owner = flat.owner,
            phonenumber = flat.owners_phonenumber,
            pure_phone = flat.owner_pure_phone
        )


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_remove_owner_own_property_alter_flat_liked_by'),
    ]

    operations = [
        migrations.RunPython(get_flat_owner)
    ]
