# Generated by Django 5.0.6 on 2024-06-14 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_auto_20240614_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='property',
            field=models.ManyToManyField(blank=True, related_name='owner_property', to='property.flat', verbose_name='Квартиры в собственности'),
        ),
    ]
